name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: "0 0 * * *"

jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        go: ['1.13', '1.14', '1.15', '1.16']

    steps:
      - name: Install protobuf
        uses: arduino/setup-protoc@v1
        with:
          version: '3.x'

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}
        id: go

      - name: Check out ygot code
        uses: actions/checkout@v2

      - name: Build packages
        run: make build

      - name: Run Tests
        run: make test

      - name: Run race tests
        run: make testrace

  static_analysis:
    name: Static Analysis
    runs-on: ubuntu-20.04

    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.15'
        id: go

      - name: Install required static analysis tools
        run: |
          go get -u github.com/go-playground/overalls
          go get -u github.com/mattn/goveralls
          go get -u honnef.co/go/tools/cmd/staticcheck

      - name: Check out ygot code
        uses: actions/checkout@v2

      - name: Get dependencies
        run: |
          make deps

      - name: Run coverage
        run: |
          overalls -project ${GITHUB_WORKSPACE} -covermode=count -ignore=".git,vendor,integration_tests,ygot/schema_tests,ygen/schema_tests,ypathgen/path_tests,demo,experimental/ygotutils,generator,ytypes/schema_tests,ypathgen/generator"

      - name: Submit coverage
        uses: shogo82148/actions-goveralls@v1
        with:
          path-to-profile: overalls.coverprofile

      - name: Go vet
        run: |
          for i in util ygen ytypes ygot/pathtranslate ypathgen; do
            go vet ./$i
          done
          for j in ygot testcmp testutil; do
            go vet -composites=false ./$j
          done

      - name: Gofmt
        run: |
          for i in util ygot ygen ytypes ygot/pathtranslate testutil testcmp ypathgen; do
            diff -u <(echo -n) <(gofmt -d -s ./$i)
          done

      - name: Staticcheck
        run: |
          checkstr=""
          for i in util ygot ygen ytypes ygot/pathtranslate testutil testcmp ypathgen; do
            checkstr="$checkstr github.com/openconfig/ygot/$i"
          done
          staticcheck $checkstr
